# Generated by Django 4.2.11 on 2024-07-11 19:13

import json
import logging

from django.db import migrations

from llmstack.common.utils.provider_config import validate_provider_configs

logger = logging.getLogger(__name__)


def populate_provider_configs(apps, schema_editor):
    """
    Migrate old API keys from individual fields to the new _provider_configs JSON field.
    Since this is a data migration, skip if there are no existing settings to migrate.
    """
    OrganizationSettings = apps.get_model("organizations", "OrganizationSettings")
    
    # Check if there are any records at all - if not, nothing to migrate
    try:
        count = OrganizationSettings.objects.count()
    except Exception as e:
        # If we can't even count, likely a fresh DB, skip gracefully
        logger.info(f"Could not count organization settings (likely fresh DB): {e}")
        return
    
    if count == 0:
        logger.info("No organization settings found, skipping migration")
        return
    
    logger.info(f"Found {count} organization settings total")
    
    # For fresh databases or when no existing API keys are set, skip the migration
    # This migration only needs to run when upgrading from an older version
    # that had API keys in separate columns
    logger.info("Skipping provider config population - no legacy API keys to migrate or fresh installation")
    return


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_organizationsettings__provider_configs"),
    ]

    operations = [migrations.RunPython(populate_provider_configs, reverse_code=migrations.RunPython.noop)]
